FROM python:3.11-slim
WORKDIR /code
RUN pip install --no-cache-dir --upgrade pip
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
ENV PYTHONUNBUFFERED=1
CMD ["celery", "-A", "app.celery_app", "worker", "--loglevel=INFO"]
